csl2leader = {
    'lijunj' : 'ZHANG Qi',
    'jingyuz' : 'JI Lijun',
    'chunxiay' : 'JI Lijun',
    'dzeng' : 'JI Lijun',
    'zhiganlu' : 'JI Lijun',
    'juanwe' : 'JI Lijun',
    'jipingw' : 'JI Lijun',
    'jinzhang' : 'JI Lijun',
    'xuejuns' : 'JI Lijun',
    'yelin' : 'JI Lijun',
    'bhe001' : 'JI Lijun',
    'jiangenz' : 'ZHANG Jingyu',
    'yggu' : 'JI Lijun',
    'yuepingz' : 'JI Lijun',
    'jzhao005' : 'JI Lijun',
    'qianz' : 'JI Lijun',
    'zhenhuz' : 'JI Lijun',
    'hongqiyu' : 'ZHANG Jingyu',
    'youaz' : 'ZHANG Jingyu',
    'lijingl' : 'ZHANG Jingyu',
    'zluo001' : 'ZHANG Jingyu',
    'yuhuabw' : 'ZHANG Jingyu',
    'tingq' : 'ZHANG Jingyu',
    'hflu' : 'ZHANG Jingyu',
    'yiminr' : 'YU Chunxiang',
    'shanchuz' : 'ZHANG Cynthia',
    'czhao011' : 'SUN Xuejun A',
    'lzhao019' : 'SUN Xuejun A',
    'mingwuz' : 'SUN Xuejun A',
    'huanliz' : 'SUN Xuejun A',
    'xyang013' : 'SUN Xuejun A',
    'lihuis' : 'SUN Xuejun A',
    'qingfens' : 'HE Bin C',
    'weiiy' : 'ZHAO Jing A',
    'lgzhao' : 'ZHANG Zhenhua',
    'yuanfz' : 'ZHANG Zhenhua',
    'ruibz' : 'ZHANG Zhenhua',
    'zongfenz' : 'ZHANG Zhenhua',
    'fangweiy' : 'ZHANG Zhenhua',
    'doyan' : 'ZHANG Zhenhua',
    'wbxie' : 'ZHANG Zhenhua',
    'mingbw' : 'ZHANG Zhenhua',
    'ludw' : 'ZHANG Zhenhua',
    'huime' : 'ZHANG Zhenhua',
    'libowa' : 'ZHANG Zhenhua',
    'zlin005' : 'ZHANG Zhenhua',
    'congm' : 'ZHANG Zhenhua',
    'xlan001' : 'ZHANG Zhenhua',
    'yunk' : 'ZHANG Zhenhua',
    'cguo005' : 'ZHANG Zhenhua',
    'yuxiad' : 'ZHANG Zhenhua',
    'jingjinc' : 'ZHANG Zhenhua',
    'xiaozhod' : 'ZHANG Zhenhua',
    'wenhaoaz' : 'ZHAO Jing A',
    'shenyuc' : 'ZHANG Zhenhua',
    'dingjiuz' : 'ZHOU Yueping',
    'kaixianx' : 'ZHOU Yueping',
    'yinliuw' : 'ZHOU Yueping',
    'jiancanx' : 'ZHOU Yueping',
    'xwang023' : 'ZHOU Yueping',
    'yzhu004' : 'ZHANG Qian',
    'bzyu' : 'ZHANG Qian',
    'qinrongx' : 'ZHANG Qian',
    'xiaoliwa' : 'ZHANG Qian',
    'fren' : 'ZHANG Qian',
    'rengangq' : 'ZHANG Qian',
    'stefliu' : 'ZHANG Qian',
    'liangchd' : 'ZHANG Qian',
    'xbxie' : 'ZHAO Jing A',
    'jingcw' : 'ZHAO Jing A',
    'yanfeiwu' : 'ZHAO Jing A',
    'zshan' : 'ZHAO Jing A',
    'zhangfel' : 'ZHAO Jing A',
    'jli069' : 'ZHAO Jing A',
    'tjian002' : 'ZHAO Jing A',
    'yguo002' : 'ZHAO Jing A',
    'dongmech' : 'ZHAO Jing A',
    'yiyingh' : 'ZHAO Jing A',
    'huaiyuzh' : 'GU Yu G',
    'weizh' : 'GU Yu G',
    'lyu013' : 'GU Yu G',
    'fye004' : 'GU Yu G',
    'peilianx' : 'GU Yu G',
    'tingew' : 'GU Yu G',
    'shaohucw' : 'GU Yu G',
    'rosong' : 'GU Yu G',
    'zaiyues' : 'GU Yu G',
    'shiquano' : 'GU Yu G',
    'yamingl' : 'GU Yu G',
    'weixw' : 'ZHOU Yueping',
    'jwang007' : 'ZHOU Yueping',
    'jitu' : 'ZHOU Yueping',
    'hutu' : 'ZHOU Yueping',
    'clin009' : 'ZHOU Yueping',
    'yuag' : 'ZHOU Yueping',
    'wafan' : 'ZHOU Yueping',
    'hailongf' : 'ZHOU Yueping',
    'xiaodoch' : 'ZHOU Yueping',
    'mchen002' : 'ZHOU Yueping',
    'junjiach' : 'ZHOU Yueping',
    'dunlongl' : 'GU Yu G',
    'yyliu' : 'GU Yu G',
    'haling' : 'GU Yu G',
    'dongdohu' : 'GU Yu G',
    'chupengh' : 'GU Yu G',
    'tuanhuif' : 'GU Yu G',
    'jianzhog' : 'GU Yu G',
    'xijc' : 'GU Yu G',
    'yundi' : 'GU Yu G',
    'shoukunc' : 'GU Yu G',
    'lunazh' : 'HE Bin C',
    'liyongca' : 'GU Yu G',
    'huihz' : 'HE Bin C',
    'wezha' : 'HE Bin C',
    'shitongx' : 'HE Bin C',
    'yingex' : 'HE Bin C',
    'lwang037' : 'HE Bin C',
    'xiaohuit' : 'HE Bin C',
    'zhaogesu' : 'HE Bin C',
    'hlu004' : 'HE Bin C',
    'pengal' : 'HE Bin C',
    'shuqinh' : 'HE Bin C',
    'jihang' : 'HE Bin C',
    'ningning' : 'HE Bin C',
    'huaey' : 'HE Bin C',
    'peijuand' : 'HE Bin C',
    'xbu' : 'HE Bin C',
    'yanjuec' : 'HE Bin C',
    'ludc' : 'HE Bin C',
    'buyunl' : 'SUN Xuejun A',
    'jfguo' : 'SUN Xuejun A',
    'xiaocaid' : 'SUN Xuejun A',
    'mhu001' : 'SUN Xuejun A',
    'jinlingy' : 'WANG Jiping',
    'meicz' : 'WANG Jiping',
    'yutingaw' : 'WANG Jiping',
    'zhiganfz' : 'WANG Jiping',
    'czuo' : 'WEN Juan',
    'huipinzh' : 'WEN Juan',
    'zhiyonz' : 'WEN Juan',
    'yantaoz' : 'WEN Juan',
    'wuzhang' : 'WEN Juan',
    'wzhan039' : 'WEN Juan',
    'donglinz' : 'WEN Juan',
    'zhengliy' : 'WEN Juan',
    'dangshzh' : 'WEN Juan',
    'fangfabw' : 'WEN Juan',
    'mengjiet' : 'WEN Juan',
    'ziqingn' : 'WEN Juan',
    'mixing' : 'ZHANG Cynthia',
    'junxingw' : 'ZHANG Cynthia',
    'jinfangw' : 'ZHANG Cynthia',
    'hemingt' : 'ZHANG Cynthia',
    'qianr' : 'ZHANG Cynthia',
    'liweid' : 'ZHANG Cynthia',
    'jbdu' : 'ZHANG Cynthia',
    'lipingc' : 'ZHANG Cynthia',
    'asun001' : 'WANG Jiping',
    'wshen005' : 'WANG Jiping',
    'yuil' : 'WANG Jiping',
    'jiangwel' : 'WANG Jiping',
    'yuanyuaj' : 'WANG Jiping',
    'weiyanh' : 'WANG Jiping',
    'zhouleih' : 'WANG Jiping',
    'yanqingg' : 'WANG Jiping',
    'lipingd' : 'WANG Jiping',
    'kaiyund' : 'WANG Jiping',
    'lisenc' : 'WANG Jiping',
    'yilv' : 'WEN Juan',
    'xiaohudl' : 'WEN Juan',
    'ylian007' : 'WEN Juan',
    'gangqial' : 'WEN Juan',
    'ruipinli' : 'WEN Juan',
    'lalan' : 'WEN Juan',
    'miracled' : 'WEN Juan',
    'zhihonji' : 'WEN Juan',
    'chunfac' : 'WEN Juan',
    'xchen043' : 'WEN Juan',
    'yzhan143' : 'LUO Zhigang',
    'yongtaoz' : 'LUO Zhigang',
    'honggz' : 'LUO Zhigang',
    'zxiuqing' : 'LUO Zhigang',
    'yanjuny' : 'LUO Zhigang',
    'yifeixi' : 'LUO Zhigang',
    'wenjuany' : 'LUO Zhigang',
    'pavolm' : 'LUO Zhigang',
    'zblin' : 'LUO Zhigang',
    'puzh' : 'ZENG Dongxu',
    'yongjiyu' : 'ZENG Dongxu',
    'yaoch' : 'ZENG Dongxu',
    'jintongy' : 'ZENG Dongxu',
    'kailiany' : 'ZENG Dongxu',
    'shenqiat' : 'ZENG Dongxu',
    'zshi' : 'ZENG Dongxu',
    'fshao001' : 'ZENG Dongxu',
    'diq' : 'ZENG Dongxu',
    'yahonglu' : 'ZENG Dongxu',
    'yliu038' : 'ZENG Dongxu',
    'jiangcl' : 'ZENG Dongxu',
    'jiamingh' : 'ZENG Dongxu',
    'huanah' : 'ZENG Dongxu',
    'zhailang' : 'ZENG Dongxu',
    'yaxiangc' : 'ZENG Dongxu',
    'mindi' : 'ZENG Dongxu',
    'guanghuw' : 'YU Chunxiang',
    'fengx' : 'YU Chunxiang',
    'feiwa' : 'YU Chunxiang',
    'qiushaz' : 'YU Chunxiang',
    'yiket' : 'YU Chunxiang',
    'xiaomant' : 'YU Chunxiang',
    'qsha' : 'YU Chunxiang',
    'jixiaop' : 'YU Chunxiang',
    'fuxingp' : 'YU Chunxiang',
    'hongbolu' : 'YU Chunxiang',
    'gangdl' : 'YU Chunxiang',
    'fangxinl' : 'YU Chunxiang',
    'sli019' : 'YU Chunxiang',
    'yjin011' : 'YU Chunxiang',
    'hongliah' : 'YU Chunxiang',
    'jiaminch' : 'YU Chunxiang',
    'lv01239' : 'YU Chunxiang',
    'lipingj' : 'ZHANG Jingyu',
    'haichuah' : 'ZHANG Jingyu',
    'jinhuah' : 'ZHANG Jingyu',
    'wgao002' : 'ZHANG Jingyu',
    'chuanpiz' : 'ZENG Dongxu',
    'qianyubl' : 'ZENG Dongxu',
    'sosnierz' : 'WRO',
    'grzyb' : 'WRO',
    'pikwiatk' : 'Lukasz',
    'wdudek' : 'WRO',
    'pmitas' : 'WRO',
    'strojnia' : 'WRO',
    'agolon' : 'WRO',
    'muszak' : 'WRO',
    'hencui' : 'HZ',
    'jungangz' : 'LING Yun',
    'bkalinow' : 'WRO',
    'tromanow' : 'Lukasz',
    'suchan' : 'WRO',
    'sworski' : 'WRO',
    'lexiang' : 'LING Yun',
    'lmarcink' : 'WRO',
    'xzhan082' : 'LING Yun',
    'songhowa' : 'LING Yun',
    'xingkail' : 'LING Yun',
    'kula' : 'WRO',
    'buczkows' : 'WRO',
    'vpilch' : 'WRO',
    'xinzhez' : 'LING Yun',
    'mlisak' : 'WRO',
    'wobarano' : 'WRO',
    'mserafin' : 'WRO',
    'kgrobeln' : 'WRO',
    'jingbg' : 'ZHANG Zhenhua',
    'zhenyuga' : 'ZHANG Zhenhua',
    'xiaoyud' : 'ZHOU Yueping',
    'pmichals' : 'WRO',
    'jiwang' : 'ZHOU Yueping',
    'kepka' : 'WRO',
    'kumor' : 'WRO',
    'kieronsk' : 'WRO',
    'rszul' : 'WRO',
    'xiaofenh' : 'SUN Xuejun A',
    'szdanowi' : 'WRO',
    'feji' : 'HZ',
    'diiliu' : 'ZHANG Zhenhua',
    'gboissel' : 'WRO',
    'shengjim' : 'ZENG Dongxu',
    'phamquoc' : 'WRO',
    'wielgus' : 'WRO',
    'tonderys' : 'WRO',
    'chrabasz' : 'WRO',
    'zhyvets' : 'WRO',
    'chojnows' : 'WRO',
    'dmitriev' : 'WRO',
    'bienczyk' : 'WRO',
    'thomalla' : 'WRO',
    'aradwans' : 'WRO',
    'lkowalcz' : 'WRO',
    'bockowsk' : 'WRO',
    'xyang011' : 'ZENG Dongxu',
    'xshi004' : 'ZHANG Zhenhua',
    'xiaocham' : 'ZENG Dongxu',
    'kobak' : 'WRO',
    'kuczaj' : 'WRO',

}